vi:
  collection_name:
  - ky ghi ro ho ten
  - ho va ten
  - ho ten
  - ten benh nhan
  collection_age:
  - tuoi
  - nam sinh
  - ngay sinh
  collection_gender:
  - phai
  - nam / nu
  - gioi tinh
  collection_follow_up:
  - tai kham
en:
  collection_name:
  - name
  collection_age:
  - age
  - date of birth
  - dob
  - birthdate
  collection_gender:
  - sex
  - gender
  collection_follow_up:
  - follow up
